### ISSUE TITLE
Debugging tiling code

### ISSUE THREAD

**Issue by y1zhou** [michaelSkaro/image_preprocessing#1]
Hey I'm trying to figure out why the tiling isn't working. Will use this issue to track the code.

First question, what's `classes`?

https://github.com/michaelSkaro/image_preprocessing/blob/1653c7d8b3ad3e27e1f04b8d26cd8ac4f4c622fd/ImageTiling.py#L157-L159

**Comment by michaelSkaro** [comment]
Got it. Added to runner

**Comment by y1zhou** [comment]
@michaelSkaro Cool it's up and running. It seems like you made `tiles` a list of lists, but all values were appended to the first child list? Also `tile` was created but never used.

https://github.com/michaelSkaro/image_preprocessing/blob/1653c7d8b3ad3e27e1f04b8d26cd8ac4f4c622fd/ImageTiling.py#L84-L105

The problem should be with the `IntersectSegmentations` function. If you uncomment:
https://github.com/michaelSkaro/image_preprocessing/blob/1653c7d8b3ad3e27e1f04b8d26cd8ac4f4c622fd/ImageTiling.py#L141

the tiled images should be created correctly, but you're overwriting the records in each iteration:

https://github.com/michaelSkaro/image_preprocessing/blob/1653c7d8b3ad3e27e1f04b8d26cd8ac4f4c622fd/ImageTiling.py#L143-L193

You should have a list of records returned, not just a dict of the last tile.

**Comment by y1zhou** [comment]
The function should be something like:

```python
def IntersectSegmentations(img_dir, output_dir, tiles, img, annotab, file):
    filename = os.path.join(img_dir, file)
    records = []
    # iterate over the tile coordinates
    for tile in tiles[0]:
        record = {}
        
        # all the operations
        ...
        records.append(record)

    return records
```

**Comment by michaelSkaro** [comment]
Thanks.
